// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh47lt3Prfthu4kTqpXR3w8PmYCsb4hKQ',
    appId: '1:834281610808:web:c608617ca5f5b2a31210cd',
    messagingSenderId: '834281610808',
    projectId: 'finalproject-e69b2',
    authDomain: 'finalproject-e69b2.firebaseapp.com',
    storageBucket: 'finalproject-e69b2.appspot.com',
    measurementId: 'G-0R187PB5N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApa5XZRMipub7mH8I3WqAhVCczZybsRus',
    appId: '1:834281610808:android:7175595a40f4226c1210cd',
    messagingSenderId: '834281610808',
    projectId: 'finalproject-e69b2',
    storageBucket: 'finalproject-e69b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqNjRM3QhwxXoz1s_63RKGq2lsObPwjk',
    appId: '1:834281610808:ios:c2c8c3809ef8119d1210cd',
    messagingSenderId: '834281610808',
    projectId: 'finalproject-e69b2',
    storageBucket: 'finalproject-e69b2.appspot.com',
    iosBundleId: 'com.example.chemlabFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArqNjRM3QhwxXoz1s_63RKGq2lsObPwjk',
    appId: '1:834281610808:ios:c2c8c3809ef8119d1210cd',
    messagingSenderId: '834281610808',
    projectId: 'finalproject-e69b2',
    storageBucket: 'finalproject-e69b2.appspot.com',
    iosBundleId: 'com.example.chemlabFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh47lt3Prfthu4kTqpXR3w8PmYCsb4hKQ',
    appId: '1:834281610808:web:404520e53cc83de41210cd',
    messagingSenderId: '834281610808',
    projectId: 'finalproject-e69b2',
    authDomain: 'finalproject-e69b2.firebaseapp.com',
    storageBucket: 'finalproject-e69b2.appspot.com',
    measurementId: 'G-48VSQBJQQW',
  );

}
